ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS login VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS users_phone_unique ON users (phone) WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS sms_codes (
    id SERIAL PRIMARY KEY,
    phone VARCHAR(20) NOT NULL,
    code VARCHAR(6) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    used BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS sms_codes_phone_idx ON sms_codes (phone);

ALTER TABLE analyses ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE pending_analyses ADD COLUMN IF NOT EXISTS email VARCHAR(255);
